### ISSUE TITLE
It's really useful for me, thanks!

### ISSUE THREAD

**Issue by fatedier** [AstromechZA/inotify-spy#1]
I try it on centos7 and it works fine.

However, it panic on centos5.10 and the kernel version is 2.6.18.

```
[wcl@os-test linux_amd64]$ ./inotify-spy /dev
Failed to setup fsnotify watcher: function not implemented
Beginning to watch events..
panic: runtime error: invalid memory address or nil pointer dereference
    panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x40 pc=0x483478]

goroutine 1 [running]:
panic(0x513e40, 0xc82000e0d0)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/AstromechZA/inotify-spy/vendor/github.com/fsnotify/fsnotify.(*Watcher).isClosed(0x0, 0x4)
    /Users/benmeier/projects/go_workspace/src/github.com/AstromechZA/inotify-spy/vendor/github.com/fsnotify/fsnotify/inotify.go:67 +0x18
github.com/AstromechZA/inotify-spy/vendor/github.com/fsnotify/fsnotify.(*Watcher).Close(0x0, 0x0, 0x0)
    /Users/benmeier/projects/go_workspace/src/github.com/AstromechZA/inotify-spy/vendor/github.com/fsnotify/fsnotify/inotify.go:76 +0x31
panic(0x513e40, 0xc82000e0d0)
    /usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/AstromechZA/inotify-spy/vendor/github.com/fsnotify/fsnotify.(*Watcher).isClosed(0x0, 0x4)
    /Users/benmeier/projects/go_workspace/src/github.com/AstromechZA/inotify-spy/vendor/github.com/fsnotify/fsnotify/inotify.go:67 +0x18
github.com/AstromechZA/inotify-spy/vendor/github.com/fsnotify/fsnotify.(*Watcher).Add(0x0, 0x7fffd7404c16, 0x4, 0x0, 0x0)
    /Users/benmeier/projects/go_workspace/src/github.com/AstromechZA/inotify-spy/vendor/github.com/fsnotify/fsnotify/inotify.go:95 +0x7a
main.main()
    /Users/benmeier/projects/go_workspace/src/github.com/AstromechZA/inotify-spy/inotifyspy.go:212 +0x1ed2
```

It seems that `github.com/fsnotify/fsnotify` can't support this kernel version but `inotify` is supported after kernel version 2.6.13.

Is there any way to let it work on centos5.10?

**Comment by astromechza** [comment]
Hi, I'll look into it, I'll also try to make sure it fails more gracefully in future.

**Comment by astromechza** [comment]
Ok I fixed the issue that threw that panic, it should just exit with code 1 now.

Unfortunately the library I'm using to hook into inotify is https://github.com/fsnotify/fsnotify which specifies "Linux 2.6.27 or later". So you might be out of luck there :/

**Comment by fatedier** [comment]
Thank you. Finally i use `strace` to hook syscall `open` to solve my problem althogh it is really trouble.
